#!/usr/bin/python
import sys
import src.training as Trainer
import src.classifier as Classifier

"""
CSCI 373 Final Project: ERG OCR

Machine learning system for reading pictures of Concept 2 Erg screens
to return data from the image in a computer-usable form.

(c) 2016 Erik Kessler
"""

HELP_TEXT = """Usage: ergocr <command>

Commands:
train <output-file> <training-image>    Train on an image
classify [k=3] <classifier> <image>     Read data from an image
"""

TRAIN_HELP = """Usage: ergoct train <output-file> <training-image>

    output-file:    file to save the classification data to
    training-image: image file to classify
"""

def train_command(args):
    if (len(args) is not 2):
        print TRAIN_HELP
    else:
        Trainer.train(args[0], args[1])

def classify_command(args):
    if (len(args) is 2):
        Classifier.classify(3, args[0], args[1])
    elif (len(args) is 3):
        Classifier.classify(int(args[0]), args[1], args[2])
    else:
        print CLASSSIFY_HELP

# dispatch to the correct method based on the command
if (len(sys.argv) == 1):
    print HELP_TEXT
elif (sys.argv[1] == "train"):
    train_command(sys.argv[2:])
elif (sys.argv[1] == "classify"):
    classify_command(sys.argv[2:])
else:
    print HELP_TEXT
